name: Create Release

on:
  push:
    #branches: [ main ]
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  #pull_request:
    #branches: [ main ]
  
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installing cxxtest
      run: sudo apt-get install -y cxxtest
    - name: Building project (Compile object file)
      run: make complex
    - name: Running tests
      run: make tests
    - name: Building App (Compile object file)
      run: make main
    - name: Zip App
      run: make main.zip
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
            Changes in this Release
            - First Change
            - Second Change
        draft: false
        prerelease: false
    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./main.zip
        asset_name: main.windows-amd64.zip
        asset_content_type: application/zip
