name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: "Installing cxxtest"
      run: sudo apt-get install -y cxxtest
    - name: "Moving to src directory"
      run: cd src
    - name: "Building project (Compile object file)"
      run: make complex
    - name: "Running tests"
      run: make tests
      
